import type { NextPage, NextPageContext } from 'next';
import Head from 'next/head';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import styles from '../../styles/Home.module.css';
import NavBar from '@components/molecules/NavBar';
import Hero from '@components/organisms/Hero';
import SocialButtons from '@molecules/SocialButtons';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <NavBar />
      <SocialButtons />

      <main className={styles.main}>
        <Hero />
      </main>
    </div>
  );
};

export default Home;

export async function getStaticProps({ locale }: NextPageContext) {
  return {
    props: {
      ...(await serverSideTranslations(locale ?? '', ['common'])),
    },
  };
}
